### ISSUE TITLE
Cerificate has expired

### ISSUE THREAD

**Issue by eiriksm** [lasselehtinen/onix-codelist#7]
Hello there!

Thanks alot for running this service. I see the certificate has expired on the site https://onix-codelists.io

Is there any way you can renew it? I would also recommend setting up automatic renewal, but I do not know anything about your hosting situation :)

Thanks again!

**Comment by lasselehtinen** [comment]
It was setup to use Let's Encrypt automatic renewals but somehow the config got broken and the renew did not happen in time. I did get notification about, but I was away for holidays. This has been now fixed and the SSL certificate is valid once gain.

**Comment by eiriksm** [comment]
🎉 

Thanks alot for the quick response. And thank you once again for making the service, and contributing your own time. It is very much appreciated :)
