### ISSUE TITLE
Issue number

### ISSUE THREAD

**Issue by gregoriopellegrino** [lasselehtinen/onix-codelist#8]
Hi,
great project! It would be useful to have the issue number for the code list, for example codelist 196 was updated on issue 46: https://ns.editeur.org/onix/en/196

Gregorio

**Comment by gregoriopellegrino** [comment]
I've seen that issue are displayed for single code, but it would be useful to know the last issue at code-list level

**Comment by lasselehtinen** [comment]
Thank you for the feedback. I just noticed that I haven't updated for a while, so I updated now to the latest issue 46.

Did I understand your question correctly, you would like to see the latest codelist issue number when any of the values was last updated?

**Comment by gregoriopellegrino** [comment]
I think that near the code-list title it would be useful to have the last issue number when it has ben updated.

Something like: <img src="https://i.ibb.co/5hM4RTN/Schermata-2019-09-25-alle-11-37-12.png" alt="Schermata-2019-09-25-alle-11-37-12" border="0">

**Comment by lasselehtinen** [comment]
I've now added it under the codelist name as a notice. Is this OK?

![image](https://user-images.githubusercontent.com/1290186/65703163-f4e1e900-e08c-11e9-94ef-01ad39669eaa.png)

**Comment by gregoriopellegrino** [comment]
Yes, great!

Thank you
